package com.cabsoft.pdf.form;

import java.io.ByteArrayOutputStream;
import java.io.OutputStream;
import java.util.HashMap;
import java.util.Iterator;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

import com.cabsoft.rx.engine.RXException;
import com.cabsoft.rx.engine.RXExporterParameter;
import com.cabsoft.rx.engine.ReportExpressPrint;
import com.cabsoft.rx.engine.export.RXPdfExporterParameter;

public class MakePdfForm {
	private static final Log log = LogFactory.getLog(MakePdfForm.class);
	
	private SignPages signPages;
	public MakePdfForm(){
		
	}
	
	public void build(OutputStream out, ReportExpressPrint rxPrint) throws Exception{
		log.debug("PDF 내보내기");
		try {
			
			PdfFormPdfExporter exporter = new PdfFormPdfExporter();
			
			//exporter.setParameter(RXPdfExporterParameter.IS_TAGGED, true);


			exporter.setParameter(RXPdfExporterParameter.PDF_VERSION, RXPdfExporterParameter.PDF_VERSION_1_7);
			
			/*
			 * 압축
			 */
			//exporter.setParameter(RXPdfExporterParameter.IS_COMPRESSED, Boolean.TRUE);
			
			// PDF 메타데이터 설정
			exporter.setParameter(RXPdfExporterParameter.METADATA_TITLE, "Test generated by ReportExpress");
			exporter.setParameter(RXPdfExporterParameter.METADATA_AUTHOR, "ReportExpress");
			exporter.setParameter(RXPdfExporterParameter.METADATA_SUBJECT, "PDF generated by ReportExpress");
			exporter.setParameter(RXPdfExporterParameter.METADATA_KEYWORDS, "ReportExpress Enterprise,Cabsoft");
			exporter.setParameter(RXPdfExporterParameter.METADATA_CREATOR, "ReportExpress");

			exporter.setParameter(RXExporterParameter.REPORTEXPRESS_PRINT, rxPrint);

			ByteArrayOutputStream o = new ByteArrayOutputStream();
			
			exporter.setParameter(RXExporterParameter.OUTPUT_STREAM, o);
			exporter.exportReport();
			
			signPages = exporter.getSignPages();
			
			o.flush();
			o.close();
			
			PdfFormValidation validation = new PdfFormValidation(o.toByteArray());
			HashMap <String, String> fields = validation.getFields();
	        Iterator<String> it = fields.keySet().iterator();
	        while(it.hasNext()){
	            String key = it.next();
	            String value = fields.get(key);
	            System.out.println(key + " = " + value);
	        }
	        
	        out.write(o.toByteArray());
	        
		} catch (RXException e) {
			throw new Exception(e);
		}
	}
	
	public SignPages getSignPages(){
		return signPages;
	}
	

}
