package com.cabsoft.smartcert;

import com.cabsoft.progress.SimpleExportProgressMonitor;
import com.cabsoft.rx.engine.RXException;
import com.cabsoft.rx.engine.RXExporterParameter;
import com.cabsoft.rx.engine.ReportExpressPrint;
import com.cabsoft.rx.engine.export.RXPdfExporter;
import com.cabsoft.rx.engine.export.RXPdfExporterParameter;
import com.cabsoft.sign.service.PdfSignTsaService;
import com.cabsoft.text.pdf.PdfWriter;
import com.cabsoft.utils.StackTrace;
import com.cabsoft.utils.SystemUtils;
import java.io.ByteArrayOutputStream;
import java.io.FileOutputStream;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import javax.servlet.ServletContext;
import javax.servlet.ServletOutputStream;
import javax.servlet.http.HttpServletResponse;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

public class SmartCertExport {
	private static final Log log = LogFactory.getLog(SmartCertExport.class);

	private SmartCertExport() {

	}

	/**
	 * PDF 내보내기
	 * 
	 * @param response
	 * @param rxPrint
	 * @param fileName
	 * @throws Exception
	 */
	public static void Pdf(String jobID, HttpServletResponse response, ReportExpressPrint rxPrint, String fileName) throws RXException, Exception {
		try {

			// String jobID, HttpServletResponse response, ReportExpressPrint
			// rxPrint, String fileName
			String fn = rxPrint.getName();
			fn = (fileName != null && !fileName.equalsIgnoreCase("")) ? fn : fileName;

			response.setContentType("application/pdf;charset=utf-8");
			response.addHeader("Content-Disposition", "attachment; filename=" + SystemUtils.getDateTime("yyyyMMdd_hhmmss") + ".pdf;");

			ServletOutputStream out = response.getOutputStream();

			RXPdfExporter exporter = new RXPdfExporter();

			// PDF 보안 설정
			exporter.setParameter(RXPdfExporterParameter.IS_ENCRYPTED, Boolean.TRUE);
			exporter.setParameter(RXPdfExporterParameter.IS_128_BIT_KEY, Boolean.TRUE);
			exporter.setParameter(RXPdfExporterParameter.OWNER_PASSWORD, "com/cabsoft");
			// exporter.setParameter(RXPdfExporterParameter.USER_PASSWORD,
			// "reports");
			exporter.setParameter(RXPdfExporterParameter.PERMISSIONS, new Integer(PdfWriter.ALLOW_PRINTING));

			// PDF 메타데이터 설정
			exporter.setParameter(RXPdfExporterParameter.METADATA_TITLE, rxPrint.getName() + " generated by ReportExpress");
			exporter.setParameter(RXPdfExporterParameter.METADATA_AUTHOR, "ReportExpress");
			exporter.setParameter(RXPdfExporterParameter.METADATA_SUBJECT, "PDF generated by ReportExpress");
			exporter.setParameter(RXPdfExporterParameter.METADATA_KEYWORDS, "ReportExpress Enterprise,Cabsoft");
			exporter.setParameter(RXPdfExporterParameter.METADATA_CREATOR, "ReportExpress");

			exporter.setParameter(RXExporterParameter.REPORTEXPRESS_PRINT, rxPrint);
			exporter.setParameter(RXExporterParameter.OUTPUT_STREAM, out);
			exporter.setParameter(RXExporterParameter.PROGRESS_MONITOR, new SimpleExportProgressMonitor(rxPrint.getName(), "PDF"));
			exporter.exportReport();
		} catch (RXException e) {
			String se = StackTrace.getStackTrace(e);
			if (se.indexOf("java.net.SocketException") > -1) {
				// log.debug("java.net.SocketException");
			} else {
				log.error(e);
				throw new Exception(e);
			}
		}
	}

	/**
	 * 전자서명된 PDF 내보내기
	 * 
	 * @param <Set>
	 * @param response
	 * @param rxPrint
	 * @param certFile
	 * @param password
	 * @throws Exception
	 */
	@SuppressWarnings("rawtypes")
	public static void Pdf(HashMap hmap) throws Exception {
		try {
			log.debug("Pdf....[Start]");
			// String OriginalName, String jobID, HttpServletResponse response,
			// ReportExpressPrint rxPrint, ServletContext context
			// Iterator iterator = hmap.entrySet().iterator();
			//
			// while(iterator. hasNext()){
			// log.debug(""+iterator.next());
			// }

			String OriginalName = (String) hmap.get("OriginalName");
			String certpasswd = (String) hmap.get("certpasswd");
			char pdfversion = (Character) (hmap.get("pdfversion").toString().charAt(0));
			boolean savepdffile = (Boolean) hmap.get("savepdffile");
			HttpServletResponse response = (HttpServletResponse) hmap.get("response");
			ReportExpressPrint rxPrint = (ReportExpressPrint) hmap.get("rxPrint");
			ServletContext context = (ServletContext) hmap.get("context");

			response.setHeader("Set-Cookie", "cabsoftfileDownload=true; path=/");
			response.setContentType("application/pdf");
			response.addHeader("Content-Disposition", "attachment; filename=" + SystemUtils.getDateTime("yyyyMMdd_hhmmss") + ".pdf");
			ServletOutputStream servletOutputStream = response.getOutputStream();

			log.debug("default PDF File........... [Start]");

			ByteArrayOutputStream byteArrayOutputStream = new ByteArrayOutputStream();
			RXPdfExporter exporter = new RXPdfExporter();

			// PDF 메타데이터 설정
			exporter.setParameter(RXPdfExporterParameter.METADATA_TITLE, rxPrint.getName() + " generated by ReportExpress");
			exporter.setParameter(RXPdfExporterParameter.METADATA_AUTHOR, "ReportExpress");
			exporter.setParameter(RXPdfExporterParameter.METADATA_SUBJECT, "PDF generated by ReportExpress");
			exporter.setParameter(RXPdfExporterParameter.METADATA_KEYWORDS, "ReportExpress Enterprise,Cabsoft");
			exporter.setParameter(RXPdfExporterParameter.METADATA_CREATOR, "ReportExpress");

			// PDF 보안 설정
			exporter.setParameter(RXPdfExporterParameter.IS_ENCRYPTED, Boolean.TRUE);
			exporter.setParameter(RXPdfExporterParameter.IS_128_BIT_KEY, Boolean.TRUE);

			/*
			 * PDF에 전자서명 및 TSA를 위해 반드시 아래의 소유자 암호로 설정해야한다.
			 */
			exporter.setParameter(RXPdfExporterParameter.OWNER_PASSWORD, "com/cabsoft");
			exporter.setParameter(RXPdfExporterParameter.PERMISSIONS, new Integer(PdfWriter.ALLOW_PRINTING));
			exporter.setParameter(RXPdfExporterParameter.PDF_VERSION, pdfversion);

			/*
			 * rxprint 클래스를 exporter에 넘겨준다.
			 */
			exporter.setParameter(RXExporterParameter.REPORTEXPRESS_PRINT, rxPrint);

			/*
			 * exporter의 결과를 byteArrayOutputStream에 넣는다.
			 */
			exporter.setParameter(RXExporterParameter.OUTPUT_STREAM, byteArrayOutputStream);

			exporter.setParameter(RXExporterParameter.PROGRESS_MONITOR, new SimpleExportProgressMonitor(rxPrint.getName(), "Signed PDF"));
			exporter.exportReport();

			byteArrayOutputStream.flush();
			byteArrayOutputStream.close();

			log.debug("default PDF File........... [End] " + byteArrayOutputStream.toByteArray().length);
			// String rxprintData =
			// com.cabsoft.pdfutils.objSerializer.ObjectToCompressedBase64(byteArrayOutputStream.toByteArray());

			/*
			 * exporter에서 저장된 PDF byteArrayOutputStream을 전자서명/TSA를 적용하여
			 * pdfByteArray에 넣는다.
			 */
			ByteArrayOutputStream pdfByteArray = new ByteArrayOutputStream();

			PdfSignTsaService.signPdf(pdfByteArray, byteArrayOutputStream, context.getRealPath("/WEB-INF/"), certpasswd);
			// RXPdfSign.signPdfWithTSAOCSP(pdfByteArray, byteArrayOutputStream,
			// context);
			pdfByteArray.flush();
			pdfByteArray.close();
			log.debug("signed/TSA PDF size: " + pdfByteArray.toByteArray().length);

			/*
			 * 전자서명/TSA가 적용된 pdfByteArray를 OriginalName 파일로 저장한다. 실제 적용에서는 파일이
			 * 아닌 데이터베이스에 저장할 수 있다.
			 * 
			 * PDF를 압축해도 파일 크기에 별 소득이 없음. PDF: 584818 byte 압축: 542740 byte
			 * Base64: 779760 byte 압축/Base64: 723656 byte
			 */
			if (savepdffile) {
				log.debug("signed/TSA PDF File Save........[Start]");
				FileOutputStream fileOutputStream = new FileOutputStream(OriginalName);
				fileOutputStream.write(pdfByteArray.toByteArray());
				fileOutputStream.flush();
				fileOutputStream.close();
			}

			servletOutputStream.write(pdfByteArray.toByteArray());
			servletOutputStream.flush();
			servletOutputStream.close();
			log.debug("Pdf....[End]");

		} catch (RXException e) {
			String se = StackTrace.getStackTrace(e);
			if (se.indexOf("java.net.SocketException") > -1) {
				// log.debug("java.net.SocketException");
			} else {
				log.error(e);
				throw new Exception(e);
			}
		}
	}

	
	@SuppressWarnings("unused")
	private static String getCurrentDate() {
		long startTime = System.currentTimeMillis();

		SimpleDateFormat sdfNow = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
		return sdfNow.format(new Date(startTime));
	}

}
