package com.cabsoft.exporters;

import java.io.OutputStream;
import java.util.Map;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import com.cabsoft.GlobalParams;
import com.cabsoft.text.pdf.ICC_Profile;
import com.cabsoft.utils.StackTrace;
import com.cabsoft.rx.engine.RXException;
import com.cabsoft.rx.engine.RXExporterParameter;
import com.cabsoft.rx.engine.ReportExpressPrint;
import com.cabsoft.rx.engine.export.RXPdfExporter;
import com.cabsoft.rx.engine.export.RXPdfExporterParameter;
import com.cabsoft.rx.engine.fill.RXAbstractLRUVirtualizer;
import com.cabsoft.rx.engine.util.RXLoader;

@SuppressWarnings("deprecation")
public class ExportPdf {
	private static final Log log = LogFactory.getLog(ExportPdf.class);

	// parameters에는 인증서 저장 경로, Timestamp 이미지 경로와 ICC Profile이 포함된다.
	Map<String, Object> parameters;
	OutputStream out;
	String jobID;
	ReportExpressPrint rxPrint;
	ICC_Profile icc = null;

	GlobalParams globalParams = null;
	boolean SignOnly = false;

	public void exportPdf(String webinf, OutputStream out, String rxPrintFile, Map<String, Object> parameters) throws Exception {
		ReportExpressPrint rxPrint = (ReportExpressPrint) RXLoader.loadObject(rxPrintFile);

		exportPdf(webinf, out, rxPrint, parameters);

	}

	public void exportPdf(String webinf, OutputStream out, ReportExpressPrint rxPrint, Map<String, Object> parameters) throws Exception {

		this.out = out;
		this.rxPrint = rxPrint;
		this.parameters = parameters;

		globalParams = GlobalParams.getInstance();

		if (globalParams == null) {
			globalParams = GlobalParams.getInstance(webinf);
		}

		String Process = (String) parameters.get("Process");
		String signOnly = (String) parameters.get("SignOnly");
		SignOnly = (signOnly != null && signOnly.equalsIgnoreCase("1")) ? true : false;
		Object virtualizer = (Object) parameters.get("virtualizer");

		log.debug("Process = " + Process);

		try {
			if (Process.equalsIgnoreCase("PDF")) {
				Pdf();
			} else if (Process.equalsIgnoreCase("PDFA")) {
				PdfA();
			}
		} catch (Exception e) {
			log.error(StackTrace.getStackTrace(e));
			throw new Exception(e);
		}

		// Virtualizer Cleanup
		try {
			if (virtualizer != null)
				((RXAbstractLRUVirtualizer) virtualizer).cleanup();
		} catch (Exception e) {
			log.error(e);
		}

	}

	/**
	 * PDF 내보내기
	 * 
	 * @param response
	 * @param rxPrint
	 * @throws Exception
	 */
	private void Pdf() throws RXException, Exception {
		log.debug("PDF 내보내기");
		try {

			RXPdfExporter exporter = new RXPdfExporter();

			exporter.setParameter(RXPdfExporterParameter.IS_TAGGED, false);

			// PDF 보안 설정
			exporter.setParameter(RXPdfExporterParameter.OWNER_PASSWORD, "com/cabsoft");
			
//			exporter.setParameter(RXPdfExporterParameter.PERMISSIONS, new Integer(PdfWriter.ALLOW_PRINTING + PdfWriter.ALLOW_SCREENREADERS));
			exporter.setParameter(RXPdfExporterParameter.PERMISSIONS, globalParams.getPdfPermision());
			

			// PDF 메타데이터 설정
			exporter.setParameter(RXPdfExporterParameter.METADATA_TITLE, 
					globalParams.getProperty("com.cabsoft.rx.pdf.title", "Test generated by ReportExpress")
			);
			exporter.setParameter(RXPdfExporterParameter.METADATA_AUTHOR, 
					globalParams.getProperty("com.cabsoft.rx.pdf.author", "ReportExpress")
			);
			exporter.setParameter(RXPdfExporterParameter.METADATA_SUBJECT, 
					globalParams.getProperty("com.cabsoft.rx.pdf.subject", "PDF generated by ReportExpress")
			);
			exporter.setParameter(RXPdfExporterParameter.METADATA_KEYWORDS, 
					globalParams.getProperty("com.cabsoft.rx.pdf.keywords", "ReportExpress Enterprise,Cabsoft")
			);
			exporter.setParameter(RXPdfExporterParameter.METADATA_CREATOR, 
					globalParams.getProperty("com.cabsoft.rx.pdf.creator", "ReportExpress")
			);

			exporter.setParameter(RXExporterParameter.REPORTEXPRESS_PRINT, rxPrint);

			// 일반 pdf
			exporter.setParameter(RXExporterParameter.OUTPUT_STREAM, out);
			exporter.exportReport();

			// // watermark pdf
			// ByteArrayOutputStream bos = new ByteArrayOutputStream();
			// exporter.setParameter(RXExporterParameter.OUTPUT_STREAM, bos);
			// exporter.exportReport();
			// bos.flush();
			// bos.close();
			//
			// ByteArrayInputStream is = new
			// ByteArrayInputStream(bos.toByteArray());
			// PdfReader reader = new PdfReader(is, "cabsoft".getBytes());
			// Watermark.InsertWatermark(out, reader,
			// context.getRealPath("/WEB-INF/")+"/properties/cabsoft/image/watermark.jpg");
			// is.close();

		} catch (RXException e) {
			throw new Exception(e);
		}
	}

	
	/**
	 * PDF/A 내보내기
	 * 
	 * @param response
	 * @param rxPrint
	 * @param icc
	 * @param certFile
	 * @param password
	 * @throws Exception
	 */
	private void PdfA() throws Exception {
		log.debug("PDF/A 내보내기");
		try {

			RXPdfExporter exporter = new RXPdfExporter();

			exporter.setParameter(RXPdfExporterParameter.PERMISSIONS, globalParams.getPdfPermision());
			
			exporter.setParameter(RXPdfExporterParameter.METADATA_TITLE, 
					globalParams.getProperty("com.cabsoft.rx.pdf.title", "Test generated by ReportExpress")
			);
			exporter.setParameter(RXPdfExporterParameter.METADATA_AUTHOR, 
					globalParams.getProperty("com.cabsoft.rx.pdf.author", "ReportExpress")
			);
			exporter.setParameter(RXPdfExporterParameter.METADATA_SUBJECT, 
					globalParams.getProperty("com.cabsoft.rx.pdf.subject", "PDF generated by ReportExpress")
			);
			exporter.setParameter(RXPdfExporterParameter.METADATA_KEYWORDS, 
					globalParams.getProperty("com.cabsoft.rx.pdf.keywords", "ReportExpress Enterprise,Cabsoft")
			);
			exporter.setParameter(RXPdfExporterParameter.METADATA_CREATOR, 
					globalParams.getProperty("com.cabsoft.rx.pdf.creator", "ReportExpress")
			);

			exporter.setParameter(RXPdfExporterParameter.ICC_PROFILE, icc);

			exporter.setParameter(RXExporterParameter.REPORTEXPRESS_PRINT, rxPrint);
			exporter.setParameter(RXPdfExporterParameter.PDF_FORMAT, "PDFA1B");

			// 전자서명을 위해 ByteArrayOutputStream로 받는다.
			exporter.setParameter(RXExporterParameter.OUTPUT_STREAM, out);
			exporter.exportReport();
		} catch (RXException e) {
			throw new Exception(e);
		}
	}

	
}
