#log4j.rootLogger=DEBUG, dailyfile2
log4j.rootLogger=ERROR, ConsoleAppender


log4j.appender.ConsoleAppender.Threshold = ERROR
log4j.appender.ConsoleAppender=org.apache.log4j.ConsoleAppender
log4j.appender.ConsoleAppender.layout=org.apache.log4j.PatternLayout
log4j.appender.ConsoleAppender.layout.ConversionPattern=[%-5p] %d{HH:mm:ss} [%c (%M:%L)] [time: %r] - %m%n

log4j.appender.dailyfile2.Threshold = ERROR
log4j.appender.dailyfile2 = org.apache.log4j.DailyRollingFileAppender
log4j.appender.dailyfile2.File = c:/logs/eform3.log
log4j.appender.rolling.DatePattern='.'yyyy-MM-dd
log4j.appender.dailyfile2.Append=true
log4j.appender.dailyfile2.layout = org.apache.log4j.PatternLayout
#log4j.appender.dailyfile2.layout.ConversionPattern=[%5p] [%c.java (%M:%L)] - %m%n
log4j.appender.dailyfile2.layout.ConversionPattern=[%-5p] %d{HH:mm:ss} [%c] [time: %r] - %m%n

log4j.logger.com.cabsoft=ERROR

