# eForm context 경로
com.cabsoft.rx.contextpath=/cdoc/eform/
com.cabsoft.rx.imagepath=/cdoc/eform/images/report/
com.cabsoft.rx.webimgurl=/cdoc/eform/images/report/

# Do not keep whole original text in print objects
com.cabsoft.rx.print.keep.full.text=true

# 보고서 및 증명서 PDF에 사용될 워터마크 설정  
com.cabsoft.rx.html.insertwatermark=true
com.cabsoft.rx.html.watermark=/image/ezloan.png
com.cabsoft.rx.smartcert.insertwatermark=false
com.cabsoft.rx.smartcert.watermark=/image/ezloan.png

# 워터마크 투명도 설정
com.cabsoft.watermark.transparancy=0.2

# PDF 검증기에서 표시될 워터마크
com.cabsoft.pdf.verify.watermark=ezloan.png

# FillListner 설정
com.cabsoft.rx.timeout=30
com.cabsoft.rx.maxpages=100
com.cabsoft.rx.interrupt=true

# Font extension character encoding
com.cabsoft.rx.fontxml.character.encoding=UTF-8

# PDF 스펙 버전
# 2 (Acrobat 3.x)   
# 3 (Acrobat 4.x)   
# 4 (Acrobat 5.x)   
# 5 (Acrobat 6.x)   
# 6 (Acrobat 7.x)   
# 7 (Acrobat 8.x)
com.cabsoft.rx.pdfversion=4

# Chart 설정
com.cabsoft.rx.chart.render.type=dpi
com.cabsoft.rx.chart.dpi=200

#다이렉트 계약시 고객이 전자서명한 데이터를 검증한 후
#인증서 정보와 서명 일자를 표시할지를 설정
com.cabsoft.ess.additional.info.visible=true

# PDF File Save
com.cabsoft.rx.pdfsign.savepdffile=false

# Security Provider 설정
com.cabsoft.rx.pdfsign.widthbc=true

# 인증서 포멧 설정
com.cabsoft.rx.pdfsign.pfx=false

# PDF에 전자서명할 인증서 설정
com.cabsoft.rx.pdfsign.certfile=eformCert
com.cabsoft.rx.pdfsign.certkeyfile=eformPri.key
com.cabsoft.rx.pdfsign.certpassword=busan2014
#com.cabsoft.rx.pdfsign.certpassword=e9993244d11ea40d9269913d6ae8ca7e

# 금융결재원 TSA를 사용하는 경우 인증서 설정
com.cabsoft.yessign.sign.cert=tsaSignCert.der
com.cabsoft.yessign.sign.privatekey=tsaSignCert.key
com.cabsoft.yessign.sign.password=qwer1234

# 보안 소켓을 사용하여 금융결재원 TSA를 사용하는 경우
com.cabsoft.yessign.km.cert=tsaKmCert.der
com.cabsoft.yessign.km.privatekey=tsaKmCert.key
com.cabsoft.yessign.km.password=qwer1234

# PDF Message Digest 알고리즘
# Use only Digital Sign and TimeStamp
#   DigestAlgorithm: SHA1, SHA-256, SHA-384, SHA-512
com.cabsoft.rx.pdfsign.messagedigestalgorithm=SHA-256

# PDF Digital Signature Properties
# Use only Digital Sign
#   SignatureAlgorithm: SHA1withRSA, SHA256withRSA, SHA384withRSA, SHA512withRSA
com.cabsoft.rx.pdfsign.signaturealgorithm=SHA256withRSA

# 기본 타임스탬프 이미지
com.cabsoft.rx.pdfsign.defaulttimestamp=2

# 인영마크가 저장된 경로
# TimeStamp Image Path: Default Path=/WEB-INF/properties/cabsoft/timestamp
com.cabsoft.rx.pdfsign.timestamppath=

# 인영 마크 및 PDF 메타데이터 설정
com.cabsoft.rx.pdf.title=eForm에 의해 생성됨
com.cabsoft.rx.pdf.author=캡소프트
com.cabsoft.rx.pdf.subject=ReportExpress eForm
com.cabsoft.rx.pdf.keywords=eForm,Cabsoft
com.cabsoft.rx.pdf.creator=ReportExpress
com.cabsoft.rx.pdfsign.stampimage=timestamp2.png
com.cabsoft.rx.pdfsign.signaturename=cabsoft
com.cabsoft.rx.pdfsign.displaystamp=true
com.cabsoft.rx.pdfsign.signercontact=support2@cabsoftware.com
com.cabsoft.rx.pdfsign.location=CABSOFTWARE.COM
com.cabsoft.rx.pdfsign.reason=eForm에 의해 전자서명된 PDF

# PDF 보안 설정
com.cabsoft.rx.pdf.allow.print=true
com.cabsoft.rx.pdf.allow.screenreaders = true
com.cabsoft.rx.pdf.allow.assembly=false
com.cabsoft.rx.pdf.allow.copy=false
com.cabsoft.rx.pdf.allow.fillin=false
com.cabsoft.rx.pdf.allow.modifyannotations=false
com.cabsoft.rx.pdf.allow.modifycontents=false

# PDF 암호화 알고리즘
# 	RC440  = RC4  40 bit
# 	RC4128 = RC4 128 bit
# 	AES128 = AES 128 bit
#	AES256 = AES 256 bit
com.cabsoft.rx.pdf.encrypt.algorithm=AES256

# Company Name
com.cabsoft.rx.pdfsign.campany=Cabsoft

#Certification Level
#	NOT_CERTIFIED = 0;
#	CERTIFIED_NO_CHANGES_ALLOWED = 1;
#	CERTIFIED_FORM_FILLING = 2;
#	CERTIFIED_FORM_FILLING_AND_ANNOTATIONS = 3;
com.cabsoft.rx.pdfsign.certificationlevel=1

# 인영 마크 위치
#	NONE = -1
#	LeftTop = 0
#	RightTop = 1
#	LeftBottom = 2
#	RightBottom = 3
com.cabsoft.rx.pdfsign.signpos=0

# TSA 
com.cabsoft.rx.pdfsign.withTSA=true
com.cabsoft.rx.pdfsign.TSASocket=true
com.cabsoft.rx.pdfsign.TSAType=yessign

# Cabsoft TSA
com.cabsoft.rx.cabsoft.TSA_URL=http://dev.cabsoftware.com:8080/tsaServer/TsaServlet
com.cabsoft.rx.cabsoft.TSA_ACCOUNT=
com.cabsoft.rx.cabsoft.TSA_PASSWORD=
com.cabsoft.cabsoft.alg=SHA-256
com.cabsoft.rx.cabsoft.withOCSP=false

# KICA TSA
com.cabsoft.rx.pdfsign.kica.url=http://61.72.247.156:4700
com.cabsoft.rx.pdfsign.kica.userid=tsaclient
com.cabsoft.rx.pdfsign.kica.password=tsaclient
com.cabsoft.rx.pdfsign.kica.alg=SHA-256

# YESSIGN TSA
com.cabsoft.yessign.url=http://203.233.91.234:7780/signedReq
com.cabsoft.yessign.userid=
com.cabsoft.yessign.password=
com.cabsoft.yessign.alg=SHA-256

# YESSIGB SOCKET
com.cabsoft.yessign.socket.server=203.233.91.234
com.cabsoft.yessign.socket.port=7779
com.cabsoft.yessign.socket.signatureAlgorithm=SHA256withRSAEncryption

# KOSCOM
com.cabsoft.koscom.url=http://211.175.81.101/tsp.php
com.cabsoft.koscom.userid=
com.cabsoft.koscom.password=
com.cabsoft.koscom.alg=SHA-256

#TSA Relay Server
com.cabsoft.tsa.relay.use=false
com.cabsoft.tsa.relay.server=127.0.0.1
com.cabsoft.tsa.relay.port=4321
com.cabsoft.tsa.relay.tsa=true

# ICC Profile for PDF/A
com.cabsoft.rx.pdfa.iccfile=sRGB.profile

# PDFA Type: 0=PDFNONE, 1=PDFX1A2001, 2=PDFX32002, 3=PDFA1A, 4=PDFA1B
com.cabsoft.rx.pdfa.type=PDFA1B

# License file using CompileManager
com.cabsoft.rx.license=/WEB-INF/properties/cabsoft/license/license.lic

com.cabsoft.rx.measure.simple.text.exact=always